dependencies:
  - conda-forge::poppler=0.67.0
  - conda-forge::geopandas=0.4.0
  - pyviz/label/dev::panel=0.2.0a8
  - pyviz/label/dev::param=1.8.2a1
  - pyviz/label/dev::geoviews=1.6.0a3
  - pyviz/label/dev::holoviews=1.11.0a10
  - pyviz/label/dev::holoviews=0.3.0a7
  - pyviz/label/dev::bokeh=1.0.0
